stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "***** starting pull from gitlab *****"
    - cd /opt/devops/data-gateway/special-symbols-request-js
    - git pull --all
    - git checkout stage
    - cd ..
    - echo "***** starting build *****"
    - docker compose build special-symbols-request-js
    - echo "***** build done *****"
  only:
    - stage


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "echo "***** starting Deploy special-symbols-request-js *****""
    - cd /opt/devops/data-gateway/
    - docker compose up -d special-symbols-request-js
    - echo "***** Application successfully deployed.*****"
  only:
    - stage
